import { useLocalSearchParams, useRouter } from 'expo-router';
import { View, Text, ScrollView, ActivityIndicator, Pressable, Share } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { StatusBar } from 'expo-status-bar';
import { useState, useEffect } from 'react';
import { getStory } from '../../lib/api';

const universeColors = {
    'Harry Potter': 'bg-amber-100',
    'Lord of the Rings': 'bg-green-100',
    'Marvel MCU': 'bg-red-100',
    'Star Wars': 'bg-yellow-100',
    'One Piece': 'bg-orange-100',
    'Naruto': 'bg-orange-50',
    'Attack on Titan': 'bg-stone-200',
    'DC': 'bg-blue-100'
};

export default function StoryView() {
    const { id } = useLocalSearchParams();
    const router = useRouter();
    const [story, setStory] = useState(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        if (id) {
            getStory(id)
                .then(setStory)
                .catch(err => {
                    console.error(err);
                })
                .finally(() => setLoading(false));
        }
    }, [id]);

    const handleShare = async () => {
        try {
            if (!story) return;
            await Share.share({
                message: `Check out this "What If" story: ${story.what_if}\n\nGenerated by What If Novel AI.`
            });
        } catch (error) {
            console.log(error);
        }
    };

    if (loading) return (
        <View className="flex-1 items-center justify-center bg-white"><ActivityIndicator size="large" color="purple" /></View>
    );

    if (!story) return (
        <View className="flex-1 items-center justify-center bg-white"><Text>Story not found.</Text></View>
    );

    const bgClass = universeColors[story.universe] || 'bg-gray-100';

    return (
        <SafeAreaView className={`flex-1 ${bgClass}`}>
            <StatusBar style="auto" />
            <ScrollView className="flex-1 px-4 py-6" contentContainerStyle={{ paddingBottom: 40 }}>
                <Pressable onPress={() => router.back()} className="mb-4 bg-white/50 self-start px-3 py-1 rounded-full">
                    <Text className="text-purple-800 font-bold">← Back</Text>
                </Pressable>

                <Text className="text-xs font-bold uppercase tracking-widest text-gray-500 mb-2 text-center">{story.universe}</Text>
                <Text className="text-2xl font-black text-gray-900 mb-4 text-center">{story.what_if}</Text>

                <View className="flex-row justify-between items-center mb-6 px-2">
                    <Text className="text-sm text-gray-500 font-medium">{story.word_count} words</Text>
                    <Pressable onPress={handleShare} className="bg-white px-4 py-2 rounded-full shadow-sm">
                        <Text className="text-blue-600 font-bold">Share 📤</Text>
                    </Pressable>
                </View>

                <View className="bg-white p-6 rounded-2xl shadow-sm mb-10">
                    <Text className="text-lg leading-8 text-gray-800 font-serif">
                        {story.story}
                    </Text>
                </View>
            </ScrollView>
        </SafeAreaView>
    );
}
