"""
Database migration script to add new columns to existing database
This preserves all existing stories while adding new features
"""
from sqlalchemy import text, inspect
from database import engine

def migrate():
    print(f"Migrating database using engine: {engine.url}")
    
    try:
        with engine.connect() as conn:
            # Create inspector to check for columns
            inspector = inspect(engine)
            columns = [col['name'] for col in inspector.get_columns('stories')]
            
            if 'share_token' not in columns:
                print("Adding share_token column...")
                # SQLite and Postgres have slightly different syntax support, 
                # but ADD COLUMN works for both in this simple case
                conn.execute(text("ALTER TABLE stories ADD COLUMN share_token VARCHAR(32)"))
                conn.commit()
                print("✓ Added share_token column")
            else:
                print("✓ share_token column already exists")
            
            # Create ratings table if it doesn't exist
            # SQLAlchemy Base.metadata.create_all(bind=engine) ensures tables exist,
            # but we can explicitly run this for safety if using raw SQL migration approach
            
            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS ratings (
                    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- Postgres compatible
                    story_id INTEGER NOT NULL,
                    session_id VARCHAR(64) NOT NULL,
                    rating_value INTEGER NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (story_id) REFERENCES stories(id)
                )
            """) if 'sqlite' not in str(engine.url) else text("""
                 CREATE TABLE IF NOT EXISTS ratings (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    story_id INTEGER NOT NULL,
                    session_id VARCHAR(64) NOT NULL,
                    rating_value INTEGER NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (story_id) REFERENCES stories(id)
                )
            """))
            conn.commit()
            print("✓ Ratings table created/verified")
            
            # Show story count
            result = conn.execute(text("SELECT COUNT(*) FROM stories"))
            count = result.scalar()
            print(f"📚 Total stories preserved: {count}")
            print("\n✅ Migration completed successfully!")
            
    except Exception as e:
        print(f"❌ Migration failed: {e}")
        # In SQLAlchemy 2.0+, rollback is often automatic on context exit with error, 
        # but manual verification is good.
        
if __name__ == "__main__":
    migrate()
