"""
Database migration script to add new columns to existing database
This preserves all existing stories while adding new features
"""
from sqlalchemy import text, inspect
from database import engine
import secrets
import sys

def migrate():
    print(f"Migrating database using engine: {engine.url}")
    
    try:
        with engine.connect() as conn:
            # Create inspector to check for columns
            inspector = inspect(engine)
            columns = [col['name'] for col in inspector.get_columns('stories')]
            print(f"Found columns in 'stories': {columns}")
            
            # 1. Add Column if missing
            if 'share_token' not in columns:
                print("Adding share_token column...")
                # SQLite and Postgres have slightly different syntax support, 
                # but ADD COLUMN works for both in this simple case
                conn.execute(text("ALTER TABLE stories ADD COLUMN share_token VARCHAR(32)"))
                conn.commit()  # Commit structural change
                print("✓ Added share_token column")
            else:
                print("✓ share_token column already exists")
            
            # 2. Backfill share_tokens for existing stories
            print("Checking for stories needing backfill...")
            # We use a transaction for data updates
            result = conn.execute(text("SELECT id FROM stories WHERE share_token IS NULL"))
            stories_to_update = result.fetchall()
            
            if stories_to_update:
                print(f"Found {len(stories_to_update)} stories without share_token. Backfilling...")
                for story_row in stories_to_update:
                    story_id = story_row[0]
                    token = secrets.token_urlsafe(16)
                    conn.execute(
                        text("UPDATE stories SET share_token = :token WHERE id = :id"),
                        {"token": token, "id": story_id}
                    )
                conn.commit()
                print(f"✓ Backfilled {len(stories_to_update)} stories with share tokens")
            else:
                print("✓ All stories already have share tokens")

            # 3. Create ratings table if it doesn't exist
            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS ratings (
                    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, -- Postgres compatible
                    story_id INTEGER NOT NULL,
                    session_id VARCHAR(64) NOT NULL,
                    rating_value INTEGER NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (story_id) REFERENCES stories(id)
                )
            """) if 'sqlite' not in str(engine.url) else text("""
                 CREATE TABLE IF NOT EXISTS ratings (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    story_id INTEGER NOT NULL,
                    session_id VARCHAR(64) NOT NULL,
                    rating_value INTEGER NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (story_id) REFERENCES stories(id)
                )
            """))
            conn.commit()
            print("✓ Ratings table created/verified")
            
            # Show story count
            result = conn.execute(text("SELECT COUNT(*) FROM stories"))
            count = result.scalar()
            print(f"📚 Total stories preserved: {count}")
            print("\n✅ Migration completed successfully!")
            
    except Exception as e:
        print(f"❌ Migration failed: {e}")
        sys.exit(1)
        
if __name__ == "__main__":
    migrate()
