import pytest
from fastapi.testclient import TestClient
from unittest.mock import patch, MagicMock
from main import app
from database import Base, engine, get_db, SessionLocal
import os

# Create a new testing database
# Since we are using SQLite, we can just use a file or in-memory.
# For simplicity with the existing setup, let's allow it to use the dev db or mock the session.
# Better to mock the session or use a test db.

# Override dependency
def override_get_db():
    try:
        db = SessionLocal()
        yield db
    finally:
        db.close()

app.dependency_overrides[get_db] = override_get_db

client = TestClient(app)

def test_read_root():
    response = client.get("/")
    assert response.status_code == 200
    data = response.json()
    assert data["message"] == "What If Novel AI API"
    assert "endpoints" in data

def test_get_universes():
    response = client.get("/universes")
    assert response.status_code == 200
    data = response.json()
    assert "universes" in data
    assert len(data["universes"]) > 0
    assert "Harry Potter" in data["universes"]

def test_get_history():
    response = client.get("/story/history")
    assert response.status_code == 200
    data = response.json()
    assert "stories" in data
    assert "count" in data

@patch("main.generate_story")
def test_generate_story(mock_generate_story):
    # Mock the AI response
    mock_generate_story.return_value = {
        "story": "This is a test story generated by pytest.",
        "word_count": 100
    }

    payload = {
        "universe": "Harry Potter",
        "what_if": "What if tests passed?",
        "length": "short"
    }
    
    response = client.post("/story/generate", json=payload)
    
    assert response.status_code == 200
    data = response.json()
    assert data["universe"] == "Harry Potter"
    assert data["what_if"] == "What if tests passed?"
    assert data["story"] == "This is a test story generated by pytest."
    assert data["word_count"] == 100
    assert "average_rating" in data
    
    # Verify it was added to history
    # note: history order might vary, checking existence
    # We access the real DB via TestClient/app, so we can verify via API
    # But ideally avoid depending on shared state. For now it's fine.

@patch("story_generator.generate_story_with_prompt")
def test_generate_custom_story(mock_generate_custom):
    mock_generate_custom.return_value = "This is a custom test story."
    
    payload = {
        "universe": "Custom World",
        "system_prompt": "You are a test bot.",
        "what_if": "What if custom works?",
        "length": "short"
    }

    response = client.post("/story/generate-custom", json=payload)
    
    assert response.status_code == 200
    data = response.json()
    assert data["universe"] == "Custom World"
    assert data["story"] == "This is a custom test story."
